# Language cn, de, en, es, fr, ru supported by default
lang: en

# Choose your database architecture <sqlite | mariadb> (if you are using mysql type in mariadb)
database_type: sqlite

# Necessary if you are using mariadb or mysql
db_name: itemex_db
db_hostname: localhost
db_port: 3306
db_username: itemex
db_passwd: Str0ngP&&7w0rt

# The Admin function creates a buy- and sellorder each item with a spread (gab between buy- and sellorder) of 100% by default. You can edit this
# variable by editing "admin_function_percentage".
admin_function: false
admin_function_spread_percentage: 100.0

# If a order will be fulfilled with the admin order, the order will be recreated with an adjusted price by that percentage value (sellorder = increase price; buyorder = decrease price)
admin_function_price_change_percentage: 10

# If there is no buy limit or sell limit order at an item, Itemex use this value for initial admin-sellorder-price and adds admin_function_percentage (default 100) to the admin-buyorder-price.
admin_function_initial_last_price: 100

# currency representation
currencySymbol: "$"
decimals: 2
decimal_separator: '.'
thousand_separator: ','
unitLocation: "right"

# If you want to charge a fee as server, you can simply edit the variable broker_fee. The value is in percentage. You can add for instance a value of 0.25 or any other.
# this fee take in place until the order will be executed
broker_fee_buyer: 0.0
broker_fee_seller: 0.0

# listing fee
sell_listing_fee: 0.0
buy_listing_fee: 0.0

# If you want to participate to share non-personalized data, please let this setting to true. It will help to improve the plugin
bstats: true

# If promote_server == true - Your server will be promoted on the Itemex Website (under construction) with the server_domain value
promote_server: false
server_domain: "play.yourdomain.com"

# With that option you are using the pre-release version of itemex with the newest features - Bug reporting is the only way to create the stable version
pre_release: true

# If this option is enabled you will get access to our Itemex Web Interface (will work like luckperms editor)
webui: true

itemex_stats: true

